Glance: use KeystoneService
openstack-k8s-operators/glance-operator pull request #16
Opened 2020-10-14 11:43 UTC by slagle

2020-10-15 13:11 UTC, stuggi requested changes
the operator needs permission to create, list, watch and update keystoneservices resources in API group keystone.openstack.org

`
		{
			APIGroups: []string{
				"keystone.openstack.org",
			},
			Resources: []string{
				"keystoneservices",
			},
			Verbs: []string{
				"list",
				"create",
				"update",
				"watch",
			},
		},
`

2020-10-15 18:46 UTC, dprince approved these changes

2020-10-19 06:49 UTC, stuggi approved these changes

2020-10-19 06:49 UTC, merged

2020-10-19 07:25 UTC, stuggi commented
I pushed new image which has this patch quay.io/openstack-k8s-operators/glance-operator:v0.0.4