Fix cinder protocols
openstack-k8s-operators/glance-operator pull request #305
Opened 2023-09-04 16:23 UTC by Akrog

This PR fixes the Cinder backend to properly support iSCSI, FC, and NVMe-oF.

The Cinder backend example present in the repository is broken, and this PR fixes it and adds an additional sample.

Depends-On: https://github.com/openstack-k8s-operators/cinder-operator/pull/259

2023-09-05 12:19 UTC, fmount requested changes

2023-09-05 12:38 UTC, Akrog commented on pkg/glance/volumes.go
> +				Name: "scripts",
Thank you for the pointer :-)
I think I'll go with making the copying optional in the Kolla config.

2023-09-05 13:37 UTC, Akrog commented
/retest

2023-09-06 07:19 UTC, fmount commented
/lgtm

2023-09-06 07:30 UTC, merged