Add default policy rules to yaml file
openstack-k8s-operators/glance-operator pull request #72
Opened 2022-10-31 14:26 UTC by konan-abhi

2022-11-02 15:00 UTC, fmount commented
@konan-abhi thanks for this patch, this is definitely aligned with the current glance deployment. To get `policy.yaml` applied to the right path (`/etc/glance` as per glance-api.conf), you have to improve this PR and add something like the following:

```
diff --git a/templates/glance/config/glance-api-config.json b/templates/glance/config/glance-api-config.json
index ef38150..6b682a3 100644
--- a/templates/glance/config/glance-api-config.json
+++ b/templates/glance/config/glance-api-config.json
@@ -30,6 +30,12 @@
         "dest": "/etc/ceph/ceph.client.{{ .User }}.keyring",
         "owner": "glance",
         "perm": "0600"
+      },
+      {
+        "source": "/var/lib/config-data/merged/policy.yaml",
+        "dest": "/etc/glance/policy.yaml",
+        "owner": "glance",
+        "perm": "0600"
       }
     ]
 }
 ```
 By doing this, when the pod starts, it copies the file to the right destination, and then it's properly applied.
 Can you try that (and test) before moving forward?

2022-11-02 15:01 UTC, fmount requested changes
We need to copy the `policy.yaml` file to the expected destination

2022-11-02 17:08 UTC, konan-abhi commented
> 

Ack, will make these changes and check whether policies are applied to API calls and then update the patch.
Thank you for explanation :+1:

2022-11-02 17:57 UTC, konan-abhi commented
Simple way to change policies are working is, create 2 more projects, create 2 users for each project (member and reader) and assign member and reader roles to these projects and users; For example as shown in https://paste.opendev.org/show/bpUROsl5E4dhYMo3KQWJ/

2022-11-07 08:27 UTC, fmount commented on templates/glance/config/glance-api-config.json
> +        "dest": "/etc/glance/glance.conf.d/policy.yaml",
Thank @konan-abhi, now I can see the right policy file being used!
I'm just wondering if a change in the README can be added to this PR so we can make sure we document how to build projects and interact w/ glance

2022-11-07 08:29 UTC, fmount commented
> Simple way to change policies are working is, create 2 more projects, create 2 users for each project (member and reader) and assign member and reader roles to these projects and users; For example as shown in https://paste.opendev.org/show/bpUROsl5E4dhYMo3KQWJ/

Maybe the pastebin can be turned into a section in the operator `README` so that people know the steps required to interact with Glance (even for CI purposes it would be useful)

2022-11-15 10:45 UTC, konan-abhi commented
Once https://github.com/openstack-k8s-operators/glance-operator/pull/83 is merged I don't think this is required.
Earlier policies were not working as the request were not piped to keystone for authentication.

Will test this once again once PR 83 is merged and if required the will reopen it.

2022-11-16 13:31 UTC, konan-abhi commented
Nope,this is still required.

2022-11-17 13:30 UTC, konan-abhi commented
@fultonj Please review, thank you!

2022-11-17 13:48 UTC, fmount approved these changes

2022-11-17 13:48 UTC, fmount commented on README.md
> +## Example: Testing Glance policies
cool, nice we have an example to keep testing the functions of the deployed `Glance` service.
From the previous conversations, I see the agreement is not to use `install_yamls` project to build project/users that can be used by the Galnce operator, but from a dev perspective, I think it's useful having a way to deploy the operator, see the service up & running, and try to list or even upload an image.
We can maybe provide a dev/ directory into hack as a place where we can store scripts (e.g. bash scripts) to help w/ development, but definitely something we can follow up later.
Thanks for this patch Abhishek!

2022-11-17 13:49 UTC, merged