add service db finalizer logic
openstack-k8s-operators/glance-operator pull request #95
Opened 2022-12-04 23:50 UTC by pinikomarov

- Bump k8s.io/apimachinery from 0.25.2 to 0.25.3
- Bump k8s.io/api from 0.25.2 to 0.25.3
- Bump k8s.io/client-go from 0.25.2 to 0.25.3
- Only add finalizer and update instance if necessary
- Bump lib-common/common to get endpoint port bug fix
- Bump github.com/onsi/gomega from 1.22.1 to 1.23.0
- Migrate from policy.json to policy.yaml
- Bump github.com/onsi/gomega from 1.23.0 to 1.24.0
- Fix defaulting PasswordSelectors
- Bump sigs.k8s.io/controller-runtime from 0.13.0 to 0.13.1
- Bump github.com/onsi/gomega from 1.24.0 to 1.24.1
- Bump k8s.io/apimachinery from 0.25.3 to 0.25.4
- Bump k8s.io/api from 0.25.3 to 0.25.4
- Bump k8s.io/client-go from 0.25.3 to 0.25.4
- Run linters on api module
- Add operator-lint make target
- Fix operator-lint rule violations
- Run operator-lint as github action
- Use service as project name instead of services
- Enable keystone authentication for glance
- Fix CRD inconsistency for glanceAPIInternal and External
- Add default policy rules to yaml file
- Add /apis directory to dependabot
- [Doc] Launch service in debug mode
- Bump k8s.io/apimachinery from 0.24.3 to 0.25.4 in /api
- Update internal/external service configuration
- use stable/zed container images
- Add OWNERS file
- Update paste_deploy config_file for zed
- Add storage devs to OWNERS
- Bump k8s.io/api from 0.24.3 to 0.25.4 in /api
- Bump sigs.k8s.io/controller-runtime from 0.12.3 to 0.13.1 in /api
- Override maxDescLen for install and deploy
- add_service_db_finalizer_logic

2022-12-09 00:29 UTC, pinikomarov commented
@fmount Hi can you please review ? 
thanks

2022-12-19 08:10 UTC, fmount requested changes

2022-12-19 08:10 UTC, fmount commented on controllers/glance_controller.go
> +	db, err := database.GetDatabaseByName(ctx, helper, instance.Name)
@pinikomarov I see that this comes from [1], so we're basically removing the finalizer checking the db entry.
LGTM, but I guess this change needs rebase first.

[1] https://github.com/openstack-k8s-operators/lib-common/pull/87

2022-12-22 16:04 UTC, fmount approved these changes

2022-12-22 16:08 UTC, fmount requested changes
CI is not happy, I suspect we need to bump lib-common if the exported function isn't available

2022-12-23 09:42 UTC, pinikomarov commented
sure I'll take another shot at the rebase

2022-12-25 09:32 UTC, pinikomarov commented
updated lib-common/modules/database to a more recent version  in go.mod , now the import thing should be fine

2022-12-31 16:07 UTC, pinikomarov commented
uploaded a cleaner version with only new code in the controller and just the updated libs (as in the keystone operator's go.mod)

2023-01-04 06:48 UTC, pinikomarov commented
/retest

2023-01-04 06:49 UTC, pinikomarov commented
@fmount does this patch need any more permissions for tests from you ? 
all good here ?

2023-01-04 07:39 UTC, stuggi commented
have you run `go mod tidy` ? seems the go.sum changes are missing

2023-01-04 13:39 UTC, pinikomarov commented
> have you run `go mod tidy` ? seems the go.sum changes are missing

I have and updated the patch with the changes it made

2023-01-04 13:58 UTC, stuggi commented
/ok-to-test

2023-01-04 14:10 UTC, stuggi approved these changes
/lgtm

2023-01-04 14:15 UTC, merged

2023-01-04 16:43 UTC, pinikomarov commented
cool, thanks